# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_path',
            field=models.ManyToManyField(related_name='_category_category_path_+', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(related_name='_category_subcategories_+', to='categories.Category'),
        ),
    ]
