# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0003_auto_20171126_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='categories.Category'),
        ),
    ]
