# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20171206_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='billing_address',
        ),
    ]
