# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_card_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='customerId',
            new_name='customer_id',
        ),
    ]
