# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Harsha Vykunta', max_length=225),
            preserve_default=False,
        ),
    ]
